apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      containers:
        - name: redis
          image: 192.168.100.1:5000/redis-cluster:latest
          readinessProbe:
            tcpSocket:
              port: 6379
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
            - name: redis-cluster
              containerPort: 16379
              protocol: TCP
            - name: redis-proxy
              containerPort: 26379
              protocol: TCP
